server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fbclone?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    open-in-view: false

app:
  jwt:
    issuer: "fbclone"
    secret-base64: "+JYFfIE2qo7eVPSFPeen6Lmn13u5JYk0JrSjo8EIPDfx1b8v+sHjmhQjPkr8FfRoVq7byo0V9gtPhYL8kMZyZQ=="
    access-token-minutes: 120
  cors:
    allowed-origins: "http://localhost:3000,http://localhost:5173"

  bootstrap-admin:
    enabled: true
    username: "admin"
    email: "admin@local"
    password: "Admin@123456"
